name: 배포

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: 노드 설정
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: 의존성 설치
        run: npm ci

      - name: 빌드
        run: npm run build

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/upload@v4

  symlink:
    needs: upload
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 체크아웃
        uses: actions/symlink@v1
