name: 빌드

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "실행할 Git 태그 (예: v1.0.0)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: 노드 설정
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: 의존성 설치
        run: npm ci

      - name: 빌드
        run: npm run build

      - name: Deploy to server
        run: |
          echo "Deploying tag ${{ github.event.inputs.tag }} to server..."
          # 실제 배포 스크립트를 여기에 추가하세요.
