name: CI
on: pull_request
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci
      - run: git branch
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: git branch
