name: CI
on: pull_request
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: 설치
        run: npm ci
      - run: npm test -- --watchAll=false
