name: CI
on: pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node -v
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: node -v
  
